# Generated by Django 4.1.5 on 2023-01-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
